eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://172.17.12.117:8761/eureka/
  instance:
    hostname: 172.17.12.117
    
spring:
 datasource:
   url: jdbc:mysql://172.17.0.212:3306/claims
   username: ndangeti
   password: Welcome1
    

